### ISSUE TITLE
Technisches Setup FE + BE

### ISSUE THREAD

**Issue by arturkurlyandski** [arturkurlyandski/gym-vergleich#1]
## Value statement - a requirement, not a solution
As a developer 
I need to see my fetch results in frontend
so that i know my database connection works
## Acceptance criteria
- [ ] The frontend shows fetch result of the database
## Tasks
- [ ] React + Symfony basic set
- [ ] Create first database entity
- [ ] GET Controller for entity
- [ ] React fetch and show results in frontend
## Size
medium
